# Generated by Django 5.1.6 on 2025-02-23 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_query_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policelog',
            name='arrest_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.arresttype'),
        ),
        migrations.AlterField(
            model_name='policelog',
            name='arrestee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.arrestee'),
        ),
        migrations.AlterField(
            model_name='policelog',
            name='charge',
            field=models.ManyToManyField(null=True, to='log_query_site.charge'),
        ),
        migrations.AlterField(
            model_name='policelog',
            name='datetime_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='policelog',
            name='datetime_stop',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='policelog',
            name='dispatch_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='policelog',
            name='dispatch_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.dispatchtype'),
        ),
        migrations.AlterField(
            model_name='policelog',
            name='disposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.disposition'),
        ),
    ]
