# Generated by Django 5.1.6 on 2025-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_query_site', '0002_alter_policelog_arrest_type_alter_policelog_arrestee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policelog',
            name='charge',
            field=models.ManyToManyField(to='log_query_site.charge'),
        ),
    ]
