# Generated by Django 5.1.6 on 2025-02-23 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrestee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('middlename', models.TextField(default='')),
                ('home_city', models.TextField()),
                ('age', models.IntegerField()),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArrestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DispatchType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Disposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=4, unique=True)),
                ('display_text', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RecordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('middlename', models.TextField(default='')),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch_number', models.IntegerField()),
                ('datetime_start', models.DateTimeField()),
                ('datetime_stop', models.DateTimeField()),
                ('address', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('arrest_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.arresttype')),
                ('arrestee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.arrestee')),
                ('charge', models.ManyToManyField(to='log_query_site.charge')),
                ('dispatch_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.dispatchtype')),
                ('disposition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.disposition')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.municipality')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.officer')),
                ('record_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='log_query_site.recordtype')),
            ],
        ),
    ]
