# Generated by Django 6.0.4 on 2026-04-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_query_site', '0004_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='policelog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policelog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
