# Generated by Django 6.0.4 on 2026-04-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_query_site', '0006_seed_record_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('error_type', models.CharField(choices=[('not_found', 'Not Found'), ('rate_limited', 'Rate Limited'), ('network_error', 'Network Error')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geocode_errors', to='log_query_site.policelog')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
